
before_script:
  - apt update
  - apt upgrade -q -y
  - pip install -r requirements.txt

stages:
  - build34
  - build35
  - build36
  - build37
  - build38

build34:
  stage: build34
  image: python:3.4
  script:
    - flake8
    - make all-clean
    - make test
  artifacts:
    paths:
      - dist/
    expire_in: 1 week

build35:
  stage: build35
  image: python:3.6
  script:
    - flake8
    - make all-clean
    - make test
  artifacts:
    paths:
      - dist/
    expire_in: 1 week

build36:
  stage: build36
  image: python:3.6
  script:
    - flake8
    - make all-clean
    - make test
  artifacts:
    paths:
      - dist/
    expire_in: 1 week

build37:
  stage: build37
  image: python:3.7
  script:
    - flake8
    - make all-clean
    - make test
  artifacts:
    paths:
      - dist/
    expire_in: 1 week

build38:
  stage: build38
  image: python:3.8
  script:
    - flake8
    - make all-clean
    - make test
  artifacts:
    paths:
      - dist/
    expire_in: 1 week
